ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('addtocart/<int:p>',views.addtocart,name="addtocart"),
    path('cart_remove/<int:p>',views.cart_remove,name="cart_remove"),
    path('full_remove/<int:p>',views.full_remove,name="full_remove"),
    path('cartview',views.cart_view,name="cartview"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
    path('searchproducts',views.searchproducts,name='searchproducts'),
]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
    path('',views.allcategories,name="allcat"),
    path('products/<int:p>',views.allproducts,name="products"),
    path('detail/<int:p>',views.showdetail,name="detail"),
    path('reg',views.register,name="register"),
    path('log',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),

]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.DateTimeField(auto_now_add=True)
    date_added=models.DateTimeField(auto_now_add=True)



    def subtotal(self):
        return self.quantity*self.product.price



    def __str__(self):
        return self.product.name

class Order(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    ordered_date=models.DateTimeField(auto_now_add=True)
    address=models.TextField()
    phone=models.BigIntegerField()
    order_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")


    def __str__(self):
        return self.user.username

class Account(models.Model):
    acctnum=models.BigIntegerField()
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):

        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import Product
from cart.models import Cart,Order,Account
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
@login_required
def cart_view(request):
    u=request.user
    total=0
    c=Cart.objects.filter(user=u)
    # To find the total amount
    for i in c:
        total=total+i.quantity*i.product.price
    return render(request, 'cart.html', {'c,':c,'total':total})


@login_required

def addtocart(request,p):
    p=Product.objects.get(id=p)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock>0):
            cart.quantity+=1
            cart.save()
            p.stock -= 1
            p.save()
    except:
        if (p.stock > 0):

            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock -= 1
            p.save()


def cart_remove(request):
    p = Product.objects.get(id=p)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        if (cart.quantity > 1):
            cart.quantity -= 1
            cart.save()
            p.stock += 1
            p.save()
        else:
            cart.delete()
            p.stock += 1
            p.save()
    except:
        pass

def full_remove(request,p):
    p = Product.objects.get(id=p)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, product=p)
        cart.delete()
        p.stock += cart.quantity
        p.save()
    except:
        pass


    return cart_view(request)

@login_required
def orderform(request):
        if (request.method=="POST"):
            a=request.POST['a']
            p=request.POST['p']
            n=request.POST['n']

            u=request.user
            c=Cart.objects.filter(user=u)


            total=0
            for i in c:
                total=total+i.quantity*i.product.price
            print(total)


            try:
                ac=Account.objects.get(acctnum=n)
                if(ac.amount >= total):
                    ac.amount=ac.amount-total
                    ac.save()
                    for i in c:
                        o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,oder_status="paid")
                        o.save()

                    c.delete()
                    msg="Order Placed Successfully"
                    print(msg)
                    return render(request, 'orderdetail.html',{'message':msg})

                else:
                    msg = "Insufficient amount.You can't place order"
                    print(msg)
                    return render(request,'orderdetail.html',{'message':msg})



            except:
                pass



        return render(request,'orderform.html')
@login_required
def orderview(request):
    u=request.user
    o=Order.objects,filter(user=u)

    return render(request,'orderview.html', {'o':o,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
def searchproducts(request):
    p=None
    query=""
    if(request.method=="POST"):
        query=request.POST['q']
        if query:
          p=Product.objects.filter(Q(name__icontains=query)| Q(desc__icontains=query))
    return render(request,'search.html',{'p':p,'q':query})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Berkshire+Swash&family=Underdog&display=swap" rel="stylesheet">

</head>
<body>
<header>
<!--<h1>Categories</h1>-->
<div class="container-fluid">
<center>
<img src="{% static 'images/ecommerce.jpg' %}" height="100px" width="120px">
</center></div>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color:#f542c2">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>

          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
            {% endfor %}
          </ul>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">Log out</a>
          </li>
          {% if user.is_superuser != True  %}
               <li class="nav-item">
                   <a class="nav-link active" aria-current="page"  style="font-size:28px;" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping">&nbsp;<sup style="font-size:30px">{{count}}</sup></i></a>
               </li>
                <li class="nav-item">
                   <a class="nav-link active" aria-current="page"  style="font-size:28px;" href="{% url 'cart:orderview' %}">Your Order </a>
               </li>
          {% endif %}


          {% else %}

          <li class="nav-item">
             <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">Register</a>
          </li>

          <li class="nav-item">
             <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">Login</a>
          </li>

          {% endif %}

         </ul>
      <form class="d-flex" method="POST" action="{% url 'search:searchproducts' %}">
          {% csrf_token %}
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
{% block content %}

{% endblock %}


<footer>
    <div style="background-color:violet;text-align:center;font-weight:bold;color:red;height:60px;width:100%;position:fixed;bottom:0;left:0;">
        <p><i class="fa-regular fa-copyright"></i>Myshop pvt ltd.All rights reserved</p>
    </div>
</footer>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% for i in c %}

<div class="container-fluid mt-3" style="margin-bottom:100px">
     <div class="row">
        <h4 class="text-center text-light">Shopping Cart</h4>
        <div class="col-7 border border-1">
            <table class="table table-bordered">
             <tr>
        <th colspan="text-center fw-bold fs-3" colspan="6">Cart Items</th>
             </tr>

                <tr>
                    <td><img src="{{i.product.image.url}}" height="150px" width="150px"></td>
                    <td><b>{{i.product.name}}</b></td>
                    <td><b>{{i.product.name}}</b></td>
                        <td><b>Product ID:{{i.product.id}}</b><br>
                        <b>Quantity:{{i.quantity}}*{{i.product.price}}</b><br>
                        <b>Unit Price:{{i.quantity}}*{{i.product.price}}</b><br></td>
                        <td> Subtotal:{{i.subtotal}}</td>
                   <td>
                       {% if i.product.stock > 0 %}
                       <a href="{% 'cart:addtocart' i.product.id %}"><i class="fa-solid fa-circle-plus me-2" style="color:blue; font-size: 25px"></i>

                           <a href="{% 'cart:carttoremove' i.product.id %}"><i class="fa-solid fa-circle-minus me-2" style="color:blue; font-size: 25px"></i></a>
                          <a href="{% 'cart:full_remove' i.product.id %}"><i class="fa-solid fa-trash me-2" style="color:blue; font-size: 25px"></i></a>

                           {% else %}
                             <a href="{% 'cart:carttoremove' i.product.id %}"><i class="fa-solid fa-circle-minus me-2" style="color:blue; font-size: 25px"></i></a>
                          <a href="{% 'cart:full_remove' i.product.id %}"><i class="fa-solid fa-trash me-2" style="color:blue; font-size: 25px"></i></a>





                           {% endif %}
                   </td>


                </tr>

                {% endfor %}

             </table>
        </div>


        <div class="col-4" style="position: relative;">
            <table class="table table-border">

                <tr>
                    <th colspan="4" class="text-center fw-bold fs-1">Check Out</th>
                </tr>
                <tr>
                    <td colspan="4">TOTAL AMOUNT:{{total}}</td>
                </tr>

            </table>

            <a class="btn btn-secondary" href="{% url 'cart.orderform' %}">Place Order</a>
            <a class="btn btn-secondary" href="{% url 'shop:allcat' %}" style="position:absolute;right:0">Continue Shopping </a>


        </div>
     </div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

 <div class="cointainer-fluid mt-1" style="margin-bottom:100px">
          <img src="{% static 'images/bgpic1.jpg' %}" height="1000px" width="100%">
 </div>
<div class="container-fluid" style="margin-bottom: 100px">
     <h3 class="text-center fn-bold">Our Collections</h3>
     <p style="text-align:justify;line-heigth:2">
Industry-leading speed
Our powerful, performance-first infrastructure ensures fast page loading to deliver an enhanced online shopping experience for your customers. Discover more about our peak performance.
"As an entrepreneur, it's really crucial to be able to build a brand that can scale worldwide. We're happy to have Wix alongside us as we scale into a larger business and do it smoothly."
</p>
</div>

<div class="container-fluid" style="margin-bottom:100px">
            <div class="row">
                {% for i in c %}
                    <div class="col-sm-4">
                                <div class="card" style="width:20rem ;">
                                <img src="{{i.image.url}}" class="card-img-top" alt="...">
                                        <div class="card-body">
                                                <h5 class="card-title">{{i.name}}</h5>
                                                <p class="card-text">{{i.desc}}</p>
                                            <a href="{% url 'shop:products' i.id %}" style="position:relative;left:15%;width:200px;" class="btn btn-secondary">Products</a>

                                        </div>
                                </div>


                    </div>

                {% endfor %}
            </div>
</div>



<div class="container-fluid style= margin-bottom:100px">
<div class="row">
    <div class="col-sm-4">
</div>
{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
  <div class="row">
   <div class="col-sm-6 mt-5">
     <img src="{{p.image.url}}" height="400px" width="400px">
     </div>
    <div class="col-sm-6 mt-5">
      <h2>{{p.name}}</h2>
      <h3>{{p.price}}</h3>
      <h3>Product Description</h3>
      <p style="text-align:justify">{{p.description}}</p>
      {% if p.stock <= 0 %}
      <h2>Out of Stock</h2>
      {% else %}
      <a href="{% url 'cart:addtocart' p.id %}" class="btn btn-primary">ADD TO CART</a>
      {% endif %}

                  </div>
      </div>
    </div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static  %}
{% block title %}

Register
{% endblock %}
{% block content %}
<div class="container" style="margin-bottom:100px">
    <h2 class="text-center"> Login .......</h2>
<form method="POST">
    {% csrf_token %}
<div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="Enter Username">
</div>
<div class="mb-3">
    <label class="form-label">Password</label>
    <input type="text" class="form-control" name="u" placeholder="Enter Password">
</div>
<div class="mb-3">
    <label class="form-label">Confirm Password</label>
    <input type="text" class="form-control" name="u" placeholder="Enter Confirm Password">
</div>
<div class="mb-3">
    <label class="form-label">Email</label>
    <input type="text" class="form-control" name="u" placeholder="Enter Email">
</div>
<div class="mb-3">
    <input type="submit" class="form-control">
</div>
</form>
</div>
{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{%  block content %}
<div class="container mt-5">
    <h4 class="text-center text-success">{{message}}</h4>
    <h6 class="text-center text-warning">Thank you.....</h6>
    <h5 class="text-center text-light"><a href="{% url 'shop:allcat' %}" class="btn btn-danger">Continue Shopping</a></h5>
</div>


{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% block content %}

<div class="container" style="margin-bottom: 100px">
    <h2 class="text-center text-light">Enter the Details......</h2>
    <form method="POST">
        {% csrf_token %}
<div class="mb-3">
    <label class="form-label">Address</label>
    <input type="text" class="form-control" name="a" placeholder="Enter Address">
</div>
<div class="mb-3">
     <label class="form-label">Phone Number</label>
    <input type="number" class="form-control" name="p" placeholder="Enter Phone Number">
</div>
<div class="mb-3">
     <label class="form-label">Account Number</label>
    <input type="number" class="form-control" name="n" placeholder="Enter Account Number">
</div>

ecommerce/templates/orderview.html
{% extends 'base.html%}

{% load static %}
<div class="container mt-5">
    <div class="row">
        <h5 class="text-center">Name of the Customer:{{u}}</h5>

        <div class="col-4 mt-3"><img src="{{i.product.image.url}}" height="150px" width="150px"></div>
        <div class="col-4 mt-3">
            <b>Productname:{{i.product.name}}</b>
            <h6>Price:{{i.product.price}}</h6>
            <h6>Quantity:{{i.product.no_of_items}}</h6>
            <h6>Address:{{i.product.address}}</h6>
            <h6>Phone:{{i.phone}}</h6>
            <h6 class="text-light fst-italic">Ordered_on:{{i.ordered_date}}</h6>
            <h6 class="text-light fst-italic">Delivery_status:{{i.delivery_status}}</h6>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <img src="{{c.image.url}}" height="400px" width="100%">
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <h1 class="text-center">{{c.name}}</h1>
    <p style="text-align:justify;">{{c.description}}</p>
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for i in product %}
        <div class="col-sm-4">
            <div class="card" style="">
                <img src="{{i.image.url}}" height="250px" width="100%" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title text-center">{{i.name}}</h5>
                    <h6 class="card-title text-center">{{i.price}}</h6>

                    <a href="{% url 'shop:prodetail' i.slug %}" class="btn btn-primary" style="position:relative;left:38%;">DETAILS</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock %}

ecommerce/templates/reg.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static  %}
{% block title %}

Register
{% endblock %}
{% block content %}
<div class="container" style="margin-bottom:100px">
    <h2 class="text-center text-light"> REGISTER HERE.......</h2>
<form method="POST">
    {% csrf_token %}
<div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="Enter Username">
</div>
<div class="mb-3">
    <label class="form-label">Password</label>
    <input type="text" class="form-control" name="u" placeholder="Enter Password">
</div>
<div class="mb-3">
    <label class="form-label">Confirm Password</label>
    <input type="text" class="form-control" name="u" placeholder="Enter Confirm Password">
</div>
<div class="mb-3">
    <label class="form-label">Email</label>
    <input type="text" class="form-control" name="u" placeholder="Enter Email">
</div>
<div class="mb-3">
    <input type="submit" class="form-control">
</div>
</form>
</div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<div class="container-fluid">
    <h3 class="text-center fw-bold">You are searched for<span class="text-warning">{{q}}</span></h3>
</div>
</center>


<div class="container-fluid" style="margin-bottom:100px">
            <div class="row">
                {% for i in p %}
                    <div class="col-sm-4 mt-4  me-1">
                                <div class="card rounded" style="width:30rem;border-width:2px;border-color: grey;">
                                    <img src="{{i.image.url}}" width="200px" heigth="200px" class="card-img-top" alt="...">
                                        <div class="card-body">
                                                <h5 class="card-title text-center">{{i.name}}</h5>
                                                <a href="{% url 'shop:detail' i.id %}" style="position:relative;left:15%;width:200px;" class="btn btn-secondary">Products</a>

                                        </div>
                                </div>
                    </div>


{% empty %}
<h5 class="text-center text-danger"> No results found</h5>


{% endfor %} </div>
             </div>

{% endblock %}